// Code generated by counterfeiter. DO NOT EDIT.
package repositoryfakes

import (
	"sync"
	"time"

	"github.com/7yrionLannister/golang-technical-assesment-v2/internal/application/repository"
	"github.com/7yrionLannister/golang-technical-assesment-v2/internal/domain/view"
)

type FakeEnergyConsumptionRepositoryInterface struct {
	GetEnergyConsumptionsByMeterIdBetweenDatesStub        func([]uint8, time.Time, time.Time) ([]view.EnergyConsumption, error)
	getEnergyConsumptionsByMeterIdBetweenDatesMutex       sync.RWMutex
	getEnergyConsumptionsByMeterIdBetweenDatesArgsForCall []struct {
		arg1 []uint8
		arg2 time.Time
		arg3 time.Time
	}
	getEnergyConsumptionsByMeterIdBetweenDatesReturns struct {
		result1 []view.EnergyConsumption
		result2 error
	}
	getEnergyConsumptionsByMeterIdBetweenDatesReturnsOnCall map[int]struct {
		result1 []view.EnergyConsumption
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeEnergyConsumptionRepositoryInterface) GetEnergyConsumptionsByMeterIdBetweenDates(arg1 []uint8, arg2 time.Time, arg3 time.Time) ([]view.EnergyConsumption, error) {
	var arg1Copy []uint8
	if arg1 != nil {
		arg1Copy = make([]uint8, len(arg1))
		copy(arg1Copy, arg1)
	}
	fake.getEnergyConsumptionsByMeterIdBetweenDatesMutex.Lock()
	ret, specificReturn := fake.getEnergyConsumptionsByMeterIdBetweenDatesReturnsOnCall[len(fake.getEnergyConsumptionsByMeterIdBetweenDatesArgsForCall)]
	fake.getEnergyConsumptionsByMeterIdBetweenDatesArgsForCall = append(fake.getEnergyConsumptionsByMeterIdBetweenDatesArgsForCall, struct {
		arg1 []uint8
		arg2 time.Time
		arg3 time.Time
	}{arg1Copy, arg2, arg3})
	stub := fake.GetEnergyConsumptionsByMeterIdBetweenDatesStub
	fakeReturns := fake.getEnergyConsumptionsByMeterIdBetweenDatesReturns
	fake.recordInvocation("GetEnergyConsumptionsByMeterIdBetweenDates", []interface{}{arg1Copy, arg2, arg3})
	fake.getEnergyConsumptionsByMeterIdBetweenDatesMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeEnergyConsumptionRepositoryInterface) GetEnergyConsumptionsByMeterIdBetweenDatesCallCount() int {
	fake.getEnergyConsumptionsByMeterIdBetweenDatesMutex.RLock()
	defer fake.getEnergyConsumptionsByMeterIdBetweenDatesMutex.RUnlock()
	return len(fake.getEnergyConsumptionsByMeterIdBetweenDatesArgsForCall)
}

func (fake *FakeEnergyConsumptionRepositoryInterface) GetEnergyConsumptionsByMeterIdBetweenDatesCalls(stub func([]uint8, time.Time, time.Time) ([]view.EnergyConsumption, error)) {
	fake.getEnergyConsumptionsByMeterIdBetweenDatesMutex.Lock()
	defer fake.getEnergyConsumptionsByMeterIdBetweenDatesMutex.Unlock()
	fake.GetEnergyConsumptionsByMeterIdBetweenDatesStub = stub
}

func (fake *FakeEnergyConsumptionRepositoryInterface) GetEnergyConsumptionsByMeterIdBetweenDatesArgsForCall(i int) ([]uint8, time.Time, time.Time) {
	fake.getEnergyConsumptionsByMeterIdBetweenDatesMutex.RLock()
	defer fake.getEnergyConsumptionsByMeterIdBetweenDatesMutex.RUnlock()
	argsForCall := fake.getEnergyConsumptionsByMeterIdBetweenDatesArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *FakeEnergyConsumptionRepositoryInterface) GetEnergyConsumptionsByMeterIdBetweenDatesReturns(result1 []view.EnergyConsumption, result2 error) {
	fake.getEnergyConsumptionsByMeterIdBetweenDatesMutex.Lock()
	defer fake.getEnergyConsumptionsByMeterIdBetweenDatesMutex.Unlock()
	fake.GetEnergyConsumptionsByMeterIdBetweenDatesStub = nil
	fake.getEnergyConsumptionsByMeterIdBetweenDatesReturns = struct {
		result1 []view.EnergyConsumption
		result2 error
	}{result1, result2}
}

func (fake *FakeEnergyConsumptionRepositoryInterface) GetEnergyConsumptionsByMeterIdBetweenDatesReturnsOnCall(i int, result1 []view.EnergyConsumption, result2 error) {
	fake.getEnergyConsumptionsByMeterIdBetweenDatesMutex.Lock()
	defer fake.getEnergyConsumptionsByMeterIdBetweenDatesMutex.Unlock()
	fake.GetEnergyConsumptionsByMeterIdBetweenDatesStub = nil
	if fake.getEnergyConsumptionsByMeterIdBetweenDatesReturnsOnCall == nil {
		fake.getEnergyConsumptionsByMeterIdBetweenDatesReturnsOnCall = make(map[int]struct {
			result1 []view.EnergyConsumption
			result2 error
		})
	}
	fake.getEnergyConsumptionsByMeterIdBetweenDatesReturnsOnCall[i] = struct {
		result1 []view.EnergyConsumption
		result2 error
	}{result1, result2}
}

func (fake *FakeEnergyConsumptionRepositoryInterface) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeEnergyConsumptionRepositoryInterface) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ repository.EnergyConsumptionRepositoryInterface = new(FakeEnergyConsumptionRepositoryInterface)
