// Code generated by counterfeiter. DO NOT EDIT.
package dbfakes

import (
	"sync"

	"github.com/7yrionLannister/golang-technical-assesment-v2/pkg/db"
)

type FakeDatabase struct {
	CreateInBatchesStub        func(any, int) error
	createInBatchesMutex       sync.RWMutex
	createInBatchesArgsForCall []struct {
		arg1 any
		arg2 int
	}
	createInBatchesReturns struct {
		result1 error
	}
	createInBatchesReturnsOnCall map[int]struct {
		result1 error
	}
	ErrorStub        func() error
	errorMutex       sync.RWMutex
	errorArgsForCall []struct {
	}
	errorReturns struct {
		result1 error
	}
	errorReturnsOnCall map[int]struct {
		result1 error
	}
	FindStub        func(any, ...any) db.Database
	findMutex       sync.RWMutex
	findArgsForCall []struct {
		arg1 any
		arg2 []any
	}
	findReturns struct {
		result1 db.Database
	}
	findReturnsOnCall map[int]struct {
		result1 db.Database
	}
	GroupStub        func(string) db.Database
	groupMutex       sync.RWMutex
	groupArgsForCall []struct {
		arg1 string
	}
	groupReturns struct {
		result1 db.Database
	}
	groupReturnsOnCall map[int]struct {
		result1 db.Database
	}
	InitDatabaseConnectionStub        func() error
	initDatabaseConnectionMutex       sync.RWMutex
	initDatabaseConnectionArgsForCall []struct {
	}
	initDatabaseConnectionReturns struct {
		result1 error
	}
	initDatabaseConnectionReturnsOnCall map[int]struct {
		result1 error
	}
	ModelStub        func(any) db.Database
	modelMutex       sync.RWMutex
	modelArgsForCall []struct {
		arg1 any
	}
	modelReturns struct {
		result1 db.Database
	}
	modelReturnsOnCall map[int]struct {
		result1 db.Database
	}
	ScanStub        func(any) db.Database
	scanMutex       sync.RWMutex
	scanArgsForCall []struct {
		arg1 any
	}
	scanReturns struct {
		result1 db.Database
	}
	scanReturnsOnCall map[int]struct {
		result1 db.Database
	}
	SelectStub        func(string, ...any) db.Database
	selectMutex       sync.RWMutex
	selectArgsForCall []struct {
		arg1 string
		arg2 []any
	}
	selectReturns struct {
		result1 db.Database
	}
	selectReturnsOnCall map[int]struct {
		result1 db.Database
	}
	WhereStub        func(string, ...any) db.Database
	whereMutex       sync.RWMutex
	whereArgsForCall []struct {
		arg1 string
		arg2 []any
	}
	whereReturns struct {
		result1 db.Database
	}
	whereReturnsOnCall map[int]struct {
		result1 db.Database
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeDatabase) CreateInBatches(arg1 any, arg2 int) error {
	fake.createInBatchesMutex.Lock()
	ret, specificReturn := fake.createInBatchesReturnsOnCall[len(fake.createInBatchesArgsForCall)]
	fake.createInBatchesArgsForCall = append(fake.createInBatchesArgsForCall, struct {
		arg1 any
		arg2 int
	}{arg1, arg2})
	stub := fake.CreateInBatchesStub
	fakeReturns := fake.createInBatchesReturns
	fake.recordInvocation("CreateInBatches", []interface{}{arg1, arg2})
	fake.createInBatchesMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeDatabase) CreateInBatchesCallCount() int {
	fake.createInBatchesMutex.RLock()
	defer fake.createInBatchesMutex.RUnlock()
	return len(fake.createInBatchesArgsForCall)
}

func (fake *FakeDatabase) CreateInBatchesCalls(stub func(any, int) error) {
	fake.createInBatchesMutex.Lock()
	defer fake.createInBatchesMutex.Unlock()
	fake.CreateInBatchesStub = stub
}

func (fake *FakeDatabase) CreateInBatchesArgsForCall(i int) (any, int) {
	fake.createInBatchesMutex.RLock()
	defer fake.createInBatchesMutex.RUnlock()
	argsForCall := fake.createInBatchesArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeDatabase) CreateInBatchesReturns(result1 error) {
	fake.createInBatchesMutex.Lock()
	defer fake.createInBatchesMutex.Unlock()
	fake.CreateInBatchesStub = nil
	fake.createInBatchesReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeDatabase) CreateInBatchesReturnsOnCall(i int, result1 error) {
	fake.createInBatchesMutex.Lock()
	defer fake.createInBatchesMutex.Unlock()
	fake.CreateInBatchesStub = nil
	if fake.createInBatchesReturnsOnCall == nil {
		fake.createInBatchesReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.createInBatchesReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeDatabase) Error() error {
	fake.errorMutex.Lock()
	ret, specificReturn := fake.errorReturnsOnCall[len(fake.errorArgsForCall)]
	fake.errorArgsForCall = append(fake.errorArgsForCall, struct {
	}{})
	stub := fake.ErrorStub
	fakeReturns := fake.errorReturns
	fake.recordInvocation("Error", []interface{}{})
	fake.errorMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeDatabase) ErrorCallCount() int {
	fake.errorMutex.RLock()
	defer fake.errorMutex.RUnlock()
	return len(fake.errorArgsForCall)
}

func (fake *FakeDatabase) ErrorCalls(stub func() error) {
	fake.errorMutex.Lock()
	defer fake.errorMutex.Unlock()
	fake.ErrorStub = stub
}

func (fake *FakeDatabase) ErrorReturns(result1 error) {
	fake.errorMutex.Lock()
	defer fake.errorMutex.Unlock()
	fake.ErrorStub = nil
	fake.errorReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeDatabase) ErrorReturnsOnCall(i int, result1 error) {
	fake.errorMutex.Lock()
	defer fake.errorMutex.Unlock()
	fake.ErrorStub = nil
	if fake.errorReturnsOnCall == nil {
		fake.errorReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.errorReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeDatabase) Find(arg1 any, arg2 ...any) db.Database {
	fake.findMutex.Lock()
	ret, specificReturn := fake.findReturnsOnCall[len(fake.findArgsForCall)]
	fake.findArgsForCall = append(fake.findArgsForCall, struct {
		arg1 any
		arg2 []any
	}{arg1, arg2})
	stub := fake.FindStub
	fakeReturns := fake.findReturns
	fake.recordInvocation("Find", []interface{}{arg1, arg2})
	fake.findMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2...)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeDatabase) FindCallCount() int {
	fake.findMutex.RLock()
	defer fake.findMutex.RUnlock()
	return len(fake.findArgsForCall)
}

func (fake *FakeDatabase) FindCalls(stub func(any, ...any) db.Database) {
	fake.findMutex.Lock()
	defer fake.findMutex.Unlock()
	fake.FindStub = stub
}

func (fake *FakeDatabase) FindArgsForCall(i int) (any, []any) {
	fake.findMutex.RLock()
	defer fake.findMutex.RUnlock()
	argsForCall := fake.findArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeDatabase) FindReturns(result1 db.Database) {
	fake.findMutex.Lock()
	defer fake.findMutex.Unlock()
	fake.FindStub = nil
	fake.findReturns = struct {
		result1 db.Database
	}{result1}
}

func (fake *FakeDatabase) FindReturnsOnCall(i int, result1 db.Database) {
	fake.findMutex.Lock()
	defer fake.findMutex.Unlock()
	fake.FindStub = nil
	if fake.findReturnsOnCall == nil {
		fake.findReturnsOnCall = make(map[int]struct {
			result1 db.Database
		})
	}
	fake.findReturnsOnCall[i] = struct {
		result1 db.Database
	}{result1}
}

func (fake *FakeDatabase) Group(arg1 string) db.Database {
	fake.groupMutex.Lock()
	ret, specificReturn := fake.groupReturnsOnCall[len(fake.groupArgsForCall)]
	fake.groupArgsForCall = append(fake.groupArgsForCall, struct {
		arg1 string
	}{arg1})
	stub := fake.GroupStub
	fakeReturns := fake.groupReturns
	fake.recordInvocation("Group", []interface{}{arg1})
	fake.groupMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeDatabase) GroupCallCount() int {
	fake.groupMutex.RLock()
	defer fake.groupMutex.RUnlock()
	return len(fake.groupArgsForCall)
}

func (fake *FakeDatabase) GroupCalls(stub func(string) db.Database) {
	fake.groupMutex.Lock()
	defer fake.groupMutex.Unlock()
	fake.GroupStub = stub
}

func (fake *FakeDatabase) GroupArgsForCall(i int) string {
	fake.groupMutex.RLock()
	defer fake.groupMutex.RUnlock()
	argsForCall := fake.groupArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeDatabase) GroupReturns(result1 db.Database) {
	fake.groupMutex.Lock()
	defer fake.groupMutex.Unlock()
	fake.GroupStub = nil
	fake.groupReturns = struct {
		result1 db.Database
	}{result1}
}

func (fake *FakeDatabase) GroupReturnsOnCall(i int, result1 db.Database) {
	fake.groupMutex.Lock()
	defer fake.groupMutex.Unlock()
	fake.GroupStub = nil
	if fake.groupReturnsOnCall == nil {
		fake.groupReturnsOnCall = make(map[int]struct {
			result1 db.Database
		})
	}
	fake.groupReturnsOnCall[i] = struct {
		result1 db.Database
	}{result1}
}

func (fake *FakeDatabase) InitDatabaseConnection() error {
	fake.initDatabaseConnectionMutex.Lock()
	ret, specificReturn := fake.initDatabaseConnectionReturnsOnCall[len(fake.initDatabaseConnectionArgsForCall)]
	fake.initDatabaseConnectionArgsForCall = append(fake.initDatabaseConnectionArgsForCall, struct {
	}{})
	stub := fake.InitDatabaseConnectionStub
	fakeReturns := fake.initDatabaseConnectionReturns
	fake.recordInvocation("InitDatabaseConnection", []interface{}{})
	fake.initDatabaseConnectionMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeDatabase) InitDatabaseConnectionCallCount() int {
	fake.initDatabaseConnectionMutex.RLock()
	defer fake.initDatabaseConnectionMutex.RUnlock()
	return len(fake.initDatabaseConnectionArgsForCall)
}

func (fake *FakeDatabase) InitDatabaseConnectionCalls(stub func() error) {
	fake.initDatabaseConnectionMutex.Lock()
	defer fake.initDatabaseConnectionMutex.Unlock()
	fake.InitDatabaseConnectionStub = stub
}

func (fake *FakeDatabase) InitDatabaseConnectionReturns(result1 error) {
	fake.initDatabaseConnectionMutex.Lock()
	defer fake.initDatabaseConnectionMutex.Unlock()
	fake.InitDatabaseConnectionStub = nil
	fake.initDatabaseConnectionReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeDatabase) InitDatabaseConnectionReturnsOnCall(i int, result1 error) {
	fake.initDatabaseConnectionMutex.Lock()
	defer fake.initDatabaseConnectionMutex.Unlock()
	fake.InitDatabaseConnectionStub = nil
	if fake.initDatabaseConnectionReturnsOnCall == nil {
		fake.initDatabaseConnectionReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.initDatabaseConnectionReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeDatabase) Model(arg1 any) db.Database {
	fake.modelMutex.Lock()
	ret, specificReturn := fake.modelReturnsOnCall[len(fake.modelArgsForCall)]
	fake.modelArgsForCall = append(fake.modelArgsForCall, struct {
		arg1 any
	}{arg1})
	stub := fake.ModelStub
	fakeReturns := fake.modelReturns
	fake.recordInvocation("Model", []interface{}{arg1})
	fake.modelMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeDatabase) ModelCallCount() int {
	fake.modelMutex.RLock()
	defer fake.modelMutex.RUnlock()
	return len(fake.modelArgsForCall)
}

func (fake *FakeDatabase) ModelCalls(stub func(any) db.Database) {
	fake.modelMutex.Lock()
	defer fake.modelMutex.Unlock()
	fake.ModelStub = stub
}

func (fake *FakeDatabase) ModelArgsForCall(i int) any {
	fake.modelMutex.RLock()
	defer fake.modelMutex.RUnlock()
	argsForCall := fake.modelArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeDatabase) ModelReturns(result1 db.Database) {
	fake.modelMutex.Lock()
	defer fake.modelMutex.Unlock()
	fake.ModelStub = nil
	fake.modelReturns = struct {
		result1 db.Database
	}{result1}
}

func (fake *FakeDatabase) ModelReturnsOnCall(i int, result1 db.Database) {
	fake.modelMutex.Lock()
	defer fake.modelMutex.Unlock()
	fake.ModelStub = nil
	if fake.modelReturnsOnCall == nil {
		fake.modelReturnsOnCall = make(map[int]struct {
			result1 db.Database
		})
	}
	fake.modelReturnsOnCall[i] = struct {
		result1 db.Database
	}{result1}
}

func (fake *FakeDatabase) Scan(arg1 any) db.Database {
	fake.scanMutex.Lock()
	ret, specificReturn := fake.scanReturnsOnCall[len(fake.scanArgsForCall)]
	fake.scanArgsForCall = append(fake.scanArgsForCall, struct {
		arg1 any
	}{arg1})
	stub := fake.ScanStub
	fakeReturns := fake.scanReturns
	fake.recordInvocation("Scan", []interface{}{arg1})
	fake.scanMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeDatabase) ScanCallCount() int {
	fake.scanMutex.RLock()
	defer fake.scanMutex.RUnlock()
	return len(fake.scanArgsForCall)
}

func (fake *FakeDatabase) ScanCalls(stub func(any) db.Database) {
	fake.scanMutex.Lock()
	defer fake.scanMutex.Unlock()
	fake.ScanStub = stub
}

func (fake *FakeDatabase) ScanArgsForCall(i int) any {
	fake.scanMutex.RLock()
	defer fake.scanMutex.RUnlock()
	argsForCall := fake.scanArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeDatabase) ScanReturns(result1 db.Database) {
	fake.scanMutex.Lock()
	defer fake.scanMutex.Unlock()
	fake.ScanStub = nil
	fake.scanReturns = struct {
		result1 db.Database
	}{result1}
}

func (fake *FakeDatabase) ScanReturnsOnCall(i int, result1 db.Database) {
	fake.scanMutex.Lock()
	defer fake.scanMutex.Unlock()
	fake.ScanStub = nil
	if fake.scanReturnsOnCall == nil {
		fake.scanReturnsOnCall = make(map[int]struct {
			result1 db.Database
		})
	}
	fake.scanReturnsOnCall[i] = struct {
		result1 db.Database
	}{result1}
}

func (fake *FakeDatabase) Select(arg1 string, arg2 ...any) db.Database {
	fake.selectMutex.Lock()
	ret, specificReturn := fake.selectReturnsOnCall[len(fake.selectArgsForCall)]
	fake.selectArgsForCall = append(fake.selectArgsForCall, struct {
		arg1 string
		arg2 []any
	}{arg1, arg2})
	stub := fake.SelectStub
	fakeReturns := fake.selectReturns
	fake.recordInvocation("Select", []interface{}{arg1, arg2})
	fake.selectMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2...)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeDatabase) SelectCallCount() int {
	fake.selectMutex.RLock()
	defer fake.selectMutex.RUnlock()
	return len(fake.selectArgsForCall)
}

func (fake *FakeDatabase) SelectCalls(stub func(string, ...any) db.Database) {
	fake.selectMutex.Lock()
	defer fake.selectMutex.Unlock()
	fake.SelectStub = stub
}

func (fake *FakeDatabase) SelectArgsForCall(i int) (string, []any) {
	fake.selectMutex.RLock()
	defer fake.selectMutex.RUnlock()
	argsForCall := fake.selectArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeDatabase) SelectReturns(result1 db.Database) {
	fake.selectMutex.Lock()
	defer fake.selectMutex.Unlock()
	fake.SelectStub = nil
	fake.selectReturns = struct {
		result1 db.Database
	}{result1}
}

func (fake *FakeDatabase) SelectReturnsOnCall(i int, result1 db.Database) {
	fake.selectMutex.Lock()
	defer fake.selectMutex.Unlock()
	fake.SelectStub = nil
	if fake.selectReturnsOnCall == nil {
		fake.selectReturnsOnCall = make(map[int]struct {
			result1 db.Database
		})
	}
	fake.selectReturnsOnCall[i] = struct {
		result1 db.Database
	}{result1}
}

func (fake *FakeDatabase) Where(arg1 string, arg2 ...any) db.Database {
	fake.whereMutex.Lock()
	ret, specificReturn := fake.whereReturnsOnCall[len(fake.whereArgsForCall)]
	fake.whereArgsForCall = append(fake.whereArgsForCall, struct {
		arg1 string
		arg2 []any
	}{arg1, arg2})
	stub := fake.WhereStub
	fakeReturns := fake.whereReturns
	fake.recordInvocation("Where", []interface{}{arg1, arg2})
	fake.whereMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2...)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeDatabase) WhereCallCount() int {
	fake.whereMutex.RLock()
	defer fake.whereMutex.RUnlock()
	return len(fake.whereArgsForCall)
}

func (fake *FakeDatabase) WhereCalls(stub func(string, ...any) db.Database) {
	fake.whereMutex.Lock()
	defer fake.whereMutex.Unlock()
	fake.WhereStub = stub
}

func (fake *FakeDatabase) WhereArgsForCall(i int) (string, []any) {
	fake.whereMutex.RLock()
	defer fake.whereMutex.RUnlock()
	argsForCall := fake.whereArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeDatabase) WhereReturns(result1 db.Database) {
	fake.whereMutex.Lock()
	defer fake.whereMutex.Unlock()
	fake.WhereStub = nil
	fake.whereReturns = struct {
		result1 db.Database
	}{result1}
}

func (fake *FakeDatabase) WhereReturnsOnCall(i int, result1 db.Database) {
	fake.whereMutex.Lock()
	defer fake.whereMutex.Unlock()
	fake.WhereStub = nil
	if fake.whereReturnsOnCall == nil {
		fake.whereReturnsOnCall = make(map[int]struct {
			result1 db.Database
		})
	}
	fake.whereReturnsOnCall[i] = struct {
		result1 db.Database
	}{result1}
}

func (fake *FakeDatabase) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeDatabase) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ db.Database = new(FakeDatabase)
