package api

// TODO: mock for unit tests
type EnergyConsumptionControllerInterface interface {
	// TODO emmbed the interface you got autogenerated
}

type EnergyConsumptionController struct{}

func (EnergyConsumptionController) TODO() {}
