//go:build go1.22

// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	externalRef0 "github.com/7yrionLannister/golang-technical-assesment-v2/internal/domain/dto"
	"github.com/getkin/kin-openapi/openapi3"
	"github.com/oapi-codegen/runtime"
	strictnethttp "github.com/oapi-codegen/runtime/strictmiddleware/nethttp"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	Bearer_authScopes = "bearer_auth.Scopes"
)

// Defines values for GetConsumptionParamsPeriod.
const (
	Daily   GetConsumptionParamsPeriod = "daily"
	Monthly GetConsumptionParamsPeriod = "monthly"
	Weekly  GetConsumptionParamsPeriod = "weekly"
)

// GetConsumptionParams defines parameters for GetConsumption.
type GetConsumptionParams struct {
	// MeterId Meter ids to filter by.
	MeterId []uint8 `form:"meter_id" json:"meter_id"`

	// StartDate Start date (format: YYYY-MM-DD).
	StartDate openapi_types.Date `form:"start_date" json:"start_date"`

	// EndDate End date (format: YYYY-MM-DD).
	EndDate openapi_types.Date `form:"end_date" json:"end_date"`

	// Period Period (any of [monthly, weekly, daily]).
	Period GetConsumptionParamsPeriod `form:"period" json:"period"`
}

// GetConsumptionParamsPeriod defines parameters for GetConsumption.
type GetConsumptionParamsPeriod string

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Get consumption report.
	// (GET /consumption)
	GetConsumption(w http.ResponseWriter, r *http.Request, params GetConsumptionParams)
	// Get OpenAPI specification
	// (GET /swagger.json)
	GetOpenapi(w http.ResponseWriter, r *http.Request)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// GetConsumption operation middleware
func (siw *ServerInterfaceWrapper) GetConsumption(w http.ResponseWriter, r *http.Request) {

	var err error

	ctx := r.Context()

	ctx = context.WithValue(ctx, Bearer_authScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params GetConsumptionParams

	// ------------- Required query parameter "meter_id" -------------

	if paramValue := r.URL.Query().Get("meter_id"); paramValue != "" {

	} else {
		siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "meter_id"})
		return
	}

	err = runtime.BindQueryParameter("form", true, true, "meter_id", r.URL.Query(), &params.MeterId)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "meter_id", Err: err})
		return
	}

	// ------------- Required query parameter "start_date" -------------

	if paramValue := r.URL.Query().Get("start_date"); paramValue != "" {

	} else {
		siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "start_date"})
		return
	}

	err = runtime.BindQueryParameter("form", true, true, "start_date", r.URL.Query(), &params.StartDate)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "start_date", Err: err})
		return
	}

	// ------------- Required query parameter "end_date" -------------

	if paramValue := r.URL.Query().Get("end_date"); paramValue != "" {

	} else {
		siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "end_date"})
		return
	}

	err = runtime.BindQueryParameter("form", true, true, "end_date", r.URL.Query(), &params.EndDate)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "end_date", Err: err})
		return
	}

	// ------------- Required query parameter "period" -------------

	if paramValue := r.URL.Query().Get("period"); paramValue != "" {

	} else {
		siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "period"})
		return
	}

	err = runtime.BindQueryParameter("form", true, true, "period", r.URL.Query(), &params.Period)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "period", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetConsumption(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetOpenapi operation middleware
func (siw *ServerInterfaceWrapper) GetOpenapi(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetOpenapi(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of http.ServeMux.
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	ServeHTTP(w http.ResponseWriter, r *http.Request)
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc("GET "+options.BaseURL+"/consumption", wrapper.GetConsumption)
	m.HandleFunc("GET "+options.BaseURL+"/swagger.json", wrapper.GetOpenapi)

	return m
}

type GetConsumptionRequestObject struct {
	Params GetConsumptionParams
}

type GetConsumptionResponseObject interface {
	VisitGetConsumptionResponse(w http.ResponseWriter) error
}

type GetConsumption200JSONResponse externalRef0.PeriodicConsumption

func (response GetConsumption200JSONResponse) VisitGetConsumptionResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetConsumption400JSONResponse externalRef0.Error

func (response GetConsumption400JSONResponse) VisitGetConsumptionResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type GetConsumption500JSONResponse externalRef0.Error

func (response GetConsumption500JSONResponse) VisitGetConsumptionResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type GetOpenapiRequestObject struct {
}

type GetOpenapiResponseObject interface {
	VisitGetOpenapiResponse(w http.ResponseWriter) error
}

type GetOpenapi200JSONResponse map[string]interface{}

func (response GetOpenapi200JSONResponse) VisitGetOpenapiResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// Get consumption report.
	// (GET /consumption)
	GetConsumption(ctx context.Context, request GetConsumptionRequestObject) (GetConsumptionResponseObject, error)
	// Get OpenAPI specification
	// (GET /swagger.json)
	GetOpenapi(ctx context.Context, request GetOpenapiRequestObject) (GetOpenapiResponseObject, error)
}

type StrictHandlerFunc = strictnethttp.StrictHTTPHandlerFunc
type StrictMiddlewareFunc = strictnethttp.StrictHTTPMiddlewareFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// GetConsumption operation middleware
func (sh *strictHandler) GetConsumption(w http.ResponseWriter, r *http.Request, params GetConsumptionParams) {
	var request GetConsumptionRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetConsumption(ctx, request.(GetConsumptionRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetConsumption")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetConsumptionResponseObject); ok {
		if err := validResponse.VisitGetConsumptionResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetOpenapi operation middleware
func (sh *strictHandler) GetOpenapi(w http.ResponseWriter, r *http.Request) {
	var request GetOpenapiRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetOpenapi(ctx, request.(GetOpenapiRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetOpenapi")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetOpenapiResponseObject); ok {
		if err := validResponse.VisitGetOpenapiResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/7xWf2/bNhD9KsRtf3SALMvu2qb6a0GSDcmWJWgKDFlgBDR1tthRpEpS8bTC3304UrH8",
	"Q0kK7AcQIKJJHd+9u/dOX0CYqjYatXeQfwEnSqx4eKxMgcrdn2m0y/bEaNdUtZdG015tTY3WSwwnufDy",
	"AempQCes7I7BcfidYYjARAiBBSQgPVbhzYWxFfeQw0IZ7iEB39YIOeimmqOF9eYHbi1vac2LwqJzA5fF",
	"DbYq0SLzJbIKPVomHVNGcB8uxj95VStCfQeT7OgoY5dcyXnDro3UPulWCTs5Zu+z6ds3MNsgcN5KvSQI",
	"Ie69LAjDVsDJLOnzaaT2R30+UntcUkLrBCx+bqTFgjB0zPVpbUXvrzbzTyh8uLqribXGHtZBmCJUYQCx",
	"c3w5tLeHJ0Tozz8D4RqtNIUUzzZGwT2/X1pel7TaVP1biwvI4Ztx33vjrvHGT3bdQC/UAcNeGeCi0cim",
	"2fQ1G7GLRrXheaCQe6lvYd1EPsx/nYBD0Vjp2xtCHPOcI7do73njy37542MvXPz2EZKoLAoVd/veKL2v",
	"YU2RpV6YWEftufAhsYpLBTkUXEtU6QKt5rrAv17/0KRSoJMpFk0qDNGxq4cPWBvrgxB2BBj2mVkwzhx6",
	"ekCFwlsppG+jZlwKCSgpULvQM5oH4Mc1FyWyaZpBAo1VHXaXj8er1SrlYTs1djnu3nXjX85Pzn69ORtN",
	"0ywtfaVCFaVXFC6WmG3VmB1fn0MCD2hdzGGSZmlG75gaNa8l5PA6nYT7a+7LwP1Y7HbgEv2hOXxA31jt",
	"nmJjYSxDLsrOMmhJJ2MXsDn6FaJmznPrT7lHxnXBUBf0TFRRy3MKdF5ADj+h3+5bgmp55BXyu31kl9Gk",
	"Cse8YQupaDVv0+BVtQqC9rZBag7I4XODtoXksSIbr9hu5Xg86mlHdi+a077C1sk+2huigBXEwasYLme3",
	"t7e3o8vL0enpd2lvsZDDNJu8G2XvRtPJxyzLw9/vMJxIoPae4j6byiaD7uSBovfxnuni69FO346yyWjy",
	"/kW0qIv/AGt0VPaK65ZUeVcZ7UvVJmyF+Af9L7hU7WwPdnfqCaSdjz2HE3VTkf/1geJ9kEC4cMg5ZxTQ",
	"1YY0TjGmWfboW6iD/HhdKymCKMafXFRmf+dXDICh+RJMcq8hGyHQuUWj2EaF1Mjf//uI4tAdwHCuH7iS",
	"BQvcs6B2Rxje/K8YPI0GxRzaB7QMu4P9uAreszOo7mZUSNdUFbdtNK4dV7RhglC7eb508fOgL8aMgo/d",
	"ii+XaNPHbF5036sa9fH1OXM1CrnoyCDjG3bSq874/2HD7U/xA/6ufo5k7ZAxiDW+HWmOht6Pwpy+NFVp",
	"nM+PsqMJEL8dd/ucXD1m6phFRZ+nNAAOZ1Pai3mb/fVs/XcAAAD//+3raTu7CwAA",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	for rawPath, rawFunc := range externalRef0.PathToRawSpec(path.Join(path.Dir(pathToFile), "./models.yaml")) {
		if _, ok := res[rawPath]; ok {
			// it is not possible to compare functions in golang, so always overwrite the old value
		}
		res[rawPath] = rawFunc
	}
	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
