//go:build go1.22

// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	externalRef0 "github.com/7yrionLannister/golang-technical-assesment-v2/internal/domain/dto"
	"github.com/getkin/kin-openapi/openapi3"
	"github.com/oapi-codegen/runtime"
	strictnethttp "github.com/oapi-codegen/runtime/strictmiddleware/nethttp"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	Bearer_authScopes = "bearer_auth.Scopes"
)

// Defines values for GetConsumptionParamsPeriod.
const (
	Daily   GetConsumptionParamsPeriod = "daily"
	Monthly GetConsumptionParamsPeriod = "monthly"
	Weekly  GetConsumptionParamsPeriod = "weekly"
)

// GetConsumptionParams defines parameters for GetConsumption.
type GetConsumptionParams struct {
	// MeterId Meter ids to filter by.
	MeterId []uint8 `form:"meter_id" json:"meter_id"`

	// StartDate Start date (format: YYYY-MM-DD).
	StartDate openapi_types.Date `form:"start_date" json:"start_date"`

	// EndDate End date (format: YYYY-MM-DD).
	EndDate openapi_types.Date `form:"end_date" json:"end_date"`

	// Period Period (any of [monthly, weekly, daily]).
	Period GetConsumptionParamsPeriod `form:"period" json:"period"`
}

// GetConsumptionParamsPeriod defines parameters for GetConsumption.
type GetConsumptionParamsPeriod string

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Get consumption report.
	// (GET /consumption)
	GetConsumption(w http.ResponseWriter, r *http.Request, params GetConsumptionParams)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// GetConsumption operation middleware
func (siw *ServerInterfaceWrapper) GetConsumption(w http.ResponseWriter, r *http.Request) {

	var err error

	ctx := r.Context()

	ctx = context.WithValue(ctx, Bearer_authScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params GetConsumptionParams

	// ------------- Required query parameter "meter_id" -------------

	if paramValue := r.URL.Query().Get("meter_id"); paramValue != "" {

	} else {
		siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "meter_id"})
		return
	}

	err = runtime.BindQueryParameter("form", true, true, "meter_id", r.URL.Query(), &params.MeterId)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "meter_id", Err: err})
		return
	}

	// ------------- Required query parameter "start_date" -------------

	if paramValue := r.URL.Query().Get("start_date"); paramValue != "" {

	} else {
		siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "start_date"})
		return
	}

	err = runtime.BindQueryParameter("form", true, true, "start_date", r.URL.Query(), &params.StartDate)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "start_date", Err: err})
		return
	}

	// ------------- Required query parameter "end_date" -------------

	if paramValue := r.URL.Query().Get("end_date"); paramValue != "" {

	} else {
		siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "end_date"})
		return
	}

	err = runtime.BindQueryParameter("form", true, true, "end_date", r.URL.Query(), &params.EndDate)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "end_date", Err: err})
		return
	}

	// ------------- Required query parameter "period" -------------

	if paramValue := r.URL.Query().Get("period"); paramValue != "" {

	} else {
		siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "period"})
		return
	}

	err = runtime.BindQueryParameter("form", true, true, "period", r.URL.Query(), &params.Period)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "period", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetConsumption(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of http.ServeMux.
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	ServeHTTP(w http.ResponseWriter, r *http.Request)
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc("GET "+options.BaseURL+"/consumption", wrapper.GetConsumption)

	return m
}

type GetConsumptionRequestObject struct {
	Params GetConsumptionParams
}

type GetConsumptionResponseObject interface {
	VisitGetConsumptionResponse(w http.ResponseWriter) error
}

type GetConsumption200JSONResponse externalRef0.PeriodicConsumption

func (response GetConsumption200JSONResponse) VisitGetConsumptionResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetConsumption400JSONResponse externalRef0.Error

func (response GetConsumption400JSONResponse) VisitGetConsumptionResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type GetConsumption500JSONResponse externalRef0.Error

func (response GetConsumption500JSONResponse) VisitGetConsumptionResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// Get consumption report.
	// (GET /consumption)
	GetConsumption(ctx context.Context, request GetConsumptionRequestObject) (GetConsumptionResponseObject, error)
}

type StrictHandlerFunc = strictnethttp.StrictHTTPHandlerFunc
type StrictMiddlewareFunc = strictnethttp.StrictHTTPMiddlewareFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// GetConsumption operation middleware
func (sh *strictHandler) GetConsumption(w http.ResponseWriter, r *http.Request, params GetConsumptionParams) {
	var request GetConsumptionRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetConsumption(ctx, request.(GetConsumptionRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetConsumption")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetConsumptionResponseObject); ok {
		if err := validResponse.VisitGetConsumptionResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/7xWYW/bNhD9K8RtHzpAlmVnbVN9WpBkQ4JlC5oCQxYYAU2eLXYUqZJUPK3wfx+OVCzb",
	"cdJ+2AoEiGhS797dvXvUZxC2bqxBEzyUn8GLCmseH2srUfv7c4Nu2Z1a49u6Ccoa2mucbdAFhfEkF0E9",
	"ID1J9MKp/hicxN8ZRgQmIgRKyEAFrOObC+tqHqCEhbY8QAahaxBKMG09RwfrzQ/cOd7Rmkvp0PsDwdIG",
	"W1XokIUKWY0BHVOeaSt4iIHxb143mljfwaQ4Pi7YFddq3rJrq0zI+lXGTk/Yu2L65jXMNgx8cMosiULE",
	"vVeSOGwBTmbZkE+rTDge8lEm4JISWmfg8FOrHEri0FduSGsLfQht5x9RhBi674lz1j3tg7AyduEAY+/5",
	"8tDeHp+IMJx/gcI1OmWlEi8KQ/LA75eONxWtNl3/3uECSvhuPGhv3Atv/KzqDmihiRz22gCXrUE2LaZH",
	"bMQuW93F5wON3Et9i+sG+Wn+6ww8itap0N0Q45TnHLlDd8/bUA3Lnx+1cPnHB8jSZBFU2h20UYXQwJqQ",
	"lVnY1EcTuAgxsZorDSVIbhTqfIHOcCPxn6Of2lwJ9CpH2ebCUjl25+E9NtaFOAg7Axj3mV0wzjwGekCN",
	"IjglVOjSzPgcMtBKoPFRM4ZH4icNFxWyaV5ABq3TPXdfjser1SrncTu3bjnu3/XjXy9Oz3+7OR9N8yKv",
	"Qq1jF1XQBJdazLZ6zE6uLyCDB3Q+5TDJi7ygd2yDhjcKSjjKJzF+w0MVaz8WuwpcYnhqDu8xtM7456qx",
	"sI4hF1VvGbSkk0kFbI5hhWiYD9yFMx6QcSMZGknPVCqSPCegCwkl/IJhW7dE1fFUVyjv9pldJZOSngXL",
	"FkrTat7l0asaHQc6uBZJHFDCpxZdB9ljRzZesS3ldDzN087YfdGc9idsne2zvaESMEk1eJXgSnZ7e3s7",
	"uroanZ39kA8WCyVMi8nbUfF2NJ18KIoy/v0JhxOJpb0n3BdT2WTQn3wy0ft8z438erbTN6NiMpq8+yJb",
	"NPJ/4Joclb3ipqOpvKutCZXuMrZC/Iv+S650N9uj3Z96hmnvYy/xRNPW5H8DUIoHGcSAh5xzRoC+sTTj",
	"hDEtikffQhPHjzeNViIOxfijT5M5xPyKC+DQ/RJNck+QrRDo/aLVbDOFJOQf/3tG6dI9wOHCPHCtJIu1",
	"Z3HaPXF4/U05BLoaNPPoHtAx7A8O11X0np2L6m5GjfRtXXPXJePacUUXbxCSW+BLnz4PhmbM1gmdwiVj",
	"G66Ekr64dGV9KI+L4wlQnB5jX/W/P3bNM4eaPtPICJ96dD6IepvFerb+NwAA//9S+MFfwwoAAA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	for rawPath, rawFunc := range externalRef0.PathToRawSpec(path.Join(path.Dir(pathToFile), "./models.yaml")) {
		if _, ok := res[rawPath]; ok {
			// it is not possible to compare functions in golang, so always overwrite the old value
		}
		res[rawPath] = rawFunc
	}
	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
