// Package dto provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package dto

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
)

// EnergyConsumption defines model for EnergyConsumption.
type EnergyConsumption struct {
	// Active Active energy consumed
	Active []float32 `json:"active"`

	// Address Address where the meter is located
	Address string `json:"address"`
	MeterId uint8  `json:"meter_id"`
}

// Error defines model for Error.
type Error struct {
	Code    string `json:"code"`
	Message string `json:"message"`
}

// PeriodicConsumption defines model for PeriodicConsumption.
type PeriodicConsumption struct {
	DataGraph []EnergyConsumption `json:"data_graph"`
	Period    []string            `json:"period"`
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/3xSTYsbMQz9K0btcZZkU1rSuYVlLwuFvS9hcWxlRmX8UVluG0L+e7ETZtJk2JtsSe89",
	"PekIJrgYPHpJ0B4hmR6druGzR+4OT8Gn7KJQ8OUzcojIQlhLtBH6jSWymAzTpQw29V9hRVCmQqCFBkjQ",
	"1c59YKcFWtgPQQs0IIeI0ILPbocMp/FDM+tDeWtrGVOaITsn1J8eGZX0qBwKsqKkhmC0VGL8q10ciuo3",
	"eFyu10v1Qw+0y+o1kJfm8mrU00Z9X66+fYXtqCAJk++KhIr7TrZouAJ83DbTPJm8rKd5yAt2ZaBTA4y/",
	"MjHaouHi3DTWFfpEHXY/0UihfmYOfL8AE2y1f0ZqSrqby90IqQhT/Rz3KzIFS+bDU7Ba9HvHOvblNe75",
	"M+MeWvi0mM5scbmxxf2Bzaw9VvIbx9/gJXtUq+Xqi3pQL3k41BgaGGP1oDa5y0nOme326vju3Pqf9Mah",
	"q8lGOfc2lS7y+wCtz8PQQIjodSRooXRp6dM5c/oXAAD//2LqOpNyAwAA",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
